name: Test Deploy Command

on:
  push:
    branches: [main]
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    env:
      DENO_DEPLOY_CLI_SPECIFIER: file://${{ github.workspace }}/main.ts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Install Dependencies
        run: deno install

      - name: test
        run: echo "${{ env.DENO_DEPLOY_ORG }}"

      - name: Test deno deploy command in astro-demo
        working-directory: ./astro-demo
        run: deno deploy --token=${{ secrets.DENO_DEPLOY_TOKEN }} --org=${{ env.DENO_DEPLOY_ORG }} --app=${{ env.DENO_DEPLOY_APP }}
